### ISSUE TITLE
falcon data replicator

### ISSUE THREAD

**Issue by saranVishva** [CrowdStrike/FDR#235]
I have few question regarding Falcon Data replicator 
1. Does crowdstrike require any specific subscription for this ?
2. Can get all the data from the crowdstrike sensor and crowdstrike console.
3. Where can I find  documentation for this ?

**Comment by ffalor** [comment]
Hey @miguelwinner182 @saranVishva, the Falcon Data Replicator documentation page in the CrowdStrike console will outline the subscriptions & what data is provided to you.

The documentation is located in the console under under:

`Falcon Documentation` > `Tools and Reference` > `Falcon Data Replicator`
